home/urls.py
from django.urls import path
from django.conf.urls import url 

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpage/', views.newpage, name='newpage'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('peserta/<int:id_peserta>', views.peserta, name='peserta'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
]

story6bintang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length = 50)

    def __str__(self):
        return "{}. {}".format(self.id, self.nama_kegiatan)

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=50, default = "")
    ikut_kegiatan = models.ForeignKey(
        Kegiatan, on_delete=models.CASCADE, null=True, blank=True
    )

home/forms.py
from django import forms


# import model dari models.py
from .models import Kegiatan, Peserta

class PostForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = [
            'nama_kegiatan',
        ]

        labels = {
            'nama_kegiatan':'Nama Kegiatan',
        }

        widgets = {
            'nama_kegiatan': forms.TextInput(
                attrs= {
                    'class':'form-control',
                    'placeholder':'Contoh: Rapat Dengar Pendapat',
                }
            ),
        }

class PostPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'nama_peserta',
        ]

        labels = {
            'nama_peserta':'Nama Peserta',
        }

        widgets = {
            'nama_peserta': forms.TextInput(
                attrs= {
                    'class':'form-control',
                    'placeholder':'Contoh: Cristiano Ronaldo',
                }
            ),
        }

home/views.py
from django.shortcuts import render, redirect

from .forms import PostForm, PostPeserta
from .models import Kegiatan, Peserta

nama_pribadi = "Bintang Samudro"

# Create your views here.

def delete(request, delete_id):
    Kegiatan.objects.filter(id=delete_id).delete()
    return redirect('home:jadwal')


def index(request):
    response = {'name' : nama_pribadi}
    return render(request, 'home/index.html', response)

def newpage(request):
    post_form = PostForm(request.POST or None)
    # error = None

    if request.method == 'POST':

        if post_form.is_valid():
            post_form.save()

            return redirect('home:jadwal')

    context = {
        'page_title':'Susun Kegiatan',
        'post_form':post_form,
    }
    return render(request, 'home/newpage.html', context)

def jadwal(request):
    posts = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    context = {
        'page_title':'List Kegiatan',
        'posts':posts,
        'peserta':peserta,
    }

    return render(request, 'home/jadwal.html', context)

def peserta(request, id_peserta):
    post_peserta = PostPeserta(request.POST or None)
    # error = None

    if request.method == 'POST':

        if post_peserta.is_valid():
            peserta = Peserta(ikut_kegiatan=Kegiatan.objects.get(id=id_peserta), nama_peserta=post_peserta.data['nama_peserta'])
            peserta.save()

            return redirect('home:jadwal')
    else:
        post_peserta = PostPeserta()

    context = {
        'page_title':'Tambah Peserta',
        'post_peserta':post_peserta,
    }
    return render(request, 'home/peserta.html', context)
    

home/templates/home/index.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}" type="text/css">
    <title>{{ name }}</title>
</head>

<body>

    {% include "includes/navbar.html" %}

    <section id="home">
        <div class="front-page">
            <img src="{% static 'home/images/Bonlap.jpg' %}" alt="No Image">
            <div class="nama">
                <h1>I am {{ name }}</h1>
            </div>
            <div class="bawahnya">
                <h5>Student of Universitas Indonesia</h5>
            </div>
        </div>
    </section>
    <section id="profile">
        <div class="container-profile">
            <div class="box-profile">
                <div class="box-profile-inside">
                    <div class="box-left-upper-bio">
                        <div class="biodata-foto">
                            <img src="{% static 'home/images/BintangSamudro.jpg' %}" alt="No Image" width="150px">
                        </div>
                        <div class="biodata-umum">
                            <p><span style="font-weight: bold;">Nama :</span> Bintang Samudro</p>
                            <p><span style="font-weight: bold;">NPM : </span> 1906399410</p>
                            <p><span style="font-weight: bold;">Jurusan</span> Sistem Informasi 2019</p>
                            <p><span style="font-weight: bold;">Email :</span> bintang.samudro@ui.ac.id</p>
                        </div>
                    </div>
                    <div class="box-left-bottom-bio">
                        <div class="skill-bar">
                            <h2>Skills</h2>
                            <ul>
                                <li class="python">Python</li>
                                <li class="java">Java</li>
                                <li class="html">HTML</li>
                                <li class="css">CSS</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="box-profile-inside-bottom">
                    <div class="box-right-title">
                        <h2 class="title">My Profile</h2>
                    </div>
                    <div class="underline-title">
                        <h2 class="underline">________________</h2>
                    </div>
                    <div class="paragraph">
                        <div class="second-paragraph">
                            Nama saya {{ name }} dari Fakultas Ilmu Komputer Universitas Indonesia, disini saya
                            ingin menjadi Full-stack Developer. Saya tinggal di Tambun Selatan dan saat kuliah offline,
                            saya tinggal di sebuah kost sehingga memudahkan saya untuk pergi kemana-mana. Hobi saya 
                            adalah bermain futsal dan berkomunikasi</div>
                        <div class="second-paragraph">Saya adalah seorang mahasiswa yang memiliki passion dalam segala
                            hal yang berhubungan dengan teknologi, oleh karena itu saya telah memutuskan tujuan saya
                            untuk membantu banyak orang dengan menggunakan teknologi. dengan ini juga membuat saya memilih jurusan
                            sistem informasi
                        </div>
                        <div class="third-paragraph">Saat ini saya menjadi bagian dari
                            DPM Fasilkom UI sebagai wakil komisi pengawas. yang bertugas membawahi BEM dan badan otonom
                            di IKM Fasilkom UI.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="background">
        <div class="container-background">
            <div class="title">
                <h1>Educational Background</h1>
            </div>
            <div class="box-educational">
                <div class="educational">
                    <div class="educational-school">
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/jasut.png' %}" width="100px"></div>
                            <div class="content">
                                <h3>SD JAYA SUTI ABADI</h3>
                                <h2>2007 ~ 2008
                                </h2>
                                <a href="https://dapo.dikdasmen.kemdikbud.go.id/sekolah/8AE8F65355DA1418F705"
                                    target="_blank">More Information</a>
                            </div>
                        </div>
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/sdlogo.png' %}" width="135px"></div>
                            <div class="content">
                                <h3>SDN SETIA DARMA 02</h3>
                                <h2>2008 ~ 2010
                                </h2>
                                <a href="https://dapo.dikdasmen.kemdikbud.go.id/sekolah/265A154A4B37077A6E8E"
                                    target="_blank">More Information</a>
                            </div>
                        </div>
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/sd.png' %}" width="102px"></div>
                            <div class="content">
                                <h3>SDIT AN-NADWAH</h3>
                                <h2>2010 ~ 2013
                                </h2>
                                <a href="http://yapiaannadwah.blogspot.com/" target="_blank">Visit Website</a>
                            </div>
                        </div>
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/smp.png' %}" width="111px"></div>
                            <div class="content">
                                <h3>SMPN 2 TAMBUN SELATAN</h3>
                                <h2>2013 ~ 2016
                                </h2>
                                <a href="https://www.smpn2tamsel.sch.id/" target="_blank">Visit Website</a>
                            </div>
                        </div>
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/sma.png' %}" width="120px"></div>
                            <div class="content">
                                <h3>SMAN 1 TAMBUN SELATAN</h3>
                                <h2>2016 ~ 2019
                                </h2>
                                <a href="https://www.smantas.sch.id/" target="_blank">Visit Website</a>
                            </div>
                        </div>
                        <div class="box-edu">
                            <div class="tingkat"><img src="{% static 'home/images/ui.png' %}" width="109px"></div>
                            <div class="content">
                                <h3>UNIVERSITAS INDONESIA</h3>
                                <h2>2019 ~ Present
                                </h2>
                                <a href="https://www.ui.ac.id/" target="_blank">Visit Website</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="fourth-page">
            <img src="{% static 'home/images/DPM.jpg' %}" alt="No Image" width="100%">
            <div class="nama">
                <h1>Utusan Angkatan 2019</h1>
            </div>
            <div class="bawahnya">
                <h5>DPM Fasilkom UI</h5>
            </div>
        </div>
    </section>

    {% include "includes/socialmedia.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

home/templates/home/jadwal.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Bintang Samudro</title>
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}" type="text/css">
</head>

<body>

    {% include "includes/navbar.html" %}

    <section id="profile">
        <h1>BIAR KENA SPACE AJA</h1>
        <h1 style="text-align: center; padding-top: 25px; border: 15px solid rgb(255, 255, 255);">{{page_title}}</h1>
        <div class="card">
            {% for post in posts %}
            <div class="border-black">
                <div class="box-card">
                    <h5 class="card-header">{{post.nama_kegiatan}}</h5>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>List Peserta : </th>
                                </tr>
                            </thead>
                            {% for orang in peserta %}
                            {% if orang.ikut_kegiatan == post %}
                            <tbody>
                                <tr>
                                    <td>{{ orang.nama_peserta }}</td>
                                </tr>
                            </tbody>
                            {% endif %}
                            {% endfor %}
                        </table>

                        <!-- Button trigger modal -->
                        <a class="btn btn-danger" href="{% url 'home:delete' post.id %}" title="">Delete</a>
                        <a class="btn btn-info" href="{% url 'home:peserta' post.id%}">Tambah Peserta</a>
                    </div>
                </div>
            </div>
            <div class="buat-nurunin-doang" style="border-top: 50px solid rgb(255, 255, 255);">
            </div>
            {% endfor %}
            <div class="buat-nurunin-doang" style="border-top: 125px solid rgb(255, 255, 255);">
                <a class="btn btn-success" href="{% url 'home:newpage' %}" title="">Buat Kegiatan Baru</a>
            </div>
        </div>
    </section>

    {% include "includes/socialmedia.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

home/templates/home/newpage.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Bintang Samudro</title>
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}" type="text/css">
</head>

<body>

    {% include "includes/navbar.html" %}

    <section id="profile">
        <h1>BIAR KENA SPACE AJA</h1>
        <h1 style="text-align: center; padding-top: 25px; border: 15px solid rgb(255, 255, 255);">{{page_title}}</h1>
        <div
            style="border-left: 55px solid rgb(255, 255, 255); border-right: 55px solid rgb(255, 255, 255); border-top: 15px solid rgb(255, 255, 255); border-bottom: 55px solid rgb(255, 255, 255);">
            <form method="POST">
                {% csrf_token %}
                {% for form in post_form %}
                <div class="form-group">
                    {{form.label}}
                    {{form}}
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        </div>
        </div>
    </section>

    {% include "includes/socialmedia.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

home/templates/home/peserta.html
<!doctype html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Bintang Samudro</title>
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}" type="text/css">
</head>

<body>

    {% include "includes/navbar.html" %}

    <section id="profile">
        <h1>BIAR KENA SPACE AJA</h1>
        <h1 style="text-align: center; padding-top: 25px; border: 15px solid rgb(255, 255, 255);">{{page_title}}</h1>
        <div
            style="border-left: 55px solid rgb(255, 255, 255); border-right: 55px solid rgb(255, 255, 255); border-top: 15px solid rgb(255, 255, 255); border-bottom: 55px solid rgb(255, 255, 255);">
            <form method="POST">
                {% csrf_token %}
                {% for form in post_peserta %}
                <div class="form-group">
                    {{form.label}}
                    {{form}}
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        </div>
        </div>
    </section>

    {% include "includes/socialmedia.html" %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

home/templates/includes/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark justify-content-center" id="navbar-background">
    <div class="navbar-brand d-flex w-50 mr-auto">
        <img src="{% static 'home/images/Logo-Bintang2.jpg' %}" alt="No Image" width="120">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
        <ul class="navbar-nav w-100 justify-content-center" id="middle-navbar">
            <li class="nav-item">
                <a class="nav-link" href="/#home">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/#profile">PROFILE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/#background">BACKGROUND</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/newpage">SUSUN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/jadwal">KEGIATAN</a>
            </li>
            
        </ul>
        <ul class="nav navbar-nav ml-auto w-100 justify-content-end" id="right-navbar">
            <li class="nav-item">
                <a class="about-me" href="#about-me"><button>ABOUT ME</button></a>
            </li>
        </ul>
    </div>
</nav>

home/templates/includes/socialmedia.html
{% load static %}

<section id="about-me">
    <div class="container-social-media">
        <div class="container-social-media-title">
            <h1>Get In Touch With Me</h1>
        </div>
        <div class="social-media-menu">
            <ul>
                <li><a href="https://www.facebook.com/bintang.samudro.319" target="_blank"><i class="fa fa-facebook"></i></a></li>
                <li><a href="https://twitter.com/samudro_bintang" target="_blank"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://www.instagram.com/bintang_samudro/?hl=en" target="_blank"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/in/bintang-samudro-180a16136/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
            </ul>
        </div>
    </div>  
</section>